### ISSUE TITLE
Errors while installing gem in raspberry pi (armv6)

### ISSUE THREAD

**Issue by vasilakisfil** [pbhogan/scrypt#23]
I get these errors as soon as bundler tries to install the scrypt gem (version 1.2.0) in my raspberry pi:
```
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    /usr/local/rvm/rubies/ruby-2.1.1/bin/ruby -rubygems /usr/local/rvm/gems/ruby-2.1.1/gems/rake-10.1.1/bin/rake RUBYARCHDIR=/usr/local/rvm/gems/ruby-2.1.1/extensions/armv6l-linux/2.1.0/scrypt-1.2.0 RUBYLIBDIR=/usr/local/rvm/gems/ruby-2.1.1/extensions/armv6l-linux/2.1.0/scrypt-1.2.0
mkdir -p arm-linux
gcc -fexceptions -O -fno-omit-frame-pointer -fno-strict-aliasing -Wall -msse -msse2 -fPIC  -o arm-linux/crypto_scrypt-sse.o -c ./crypto_scrypt-sse.c
cc1: error: unrecognized command line option '-msse'
cc1: error: unrecognized command line option '-msse2'
rake aborted!
Command failed with status (1): [gcc -fexceptions -O -fno-omit-frame-pointe...]
/usr/local/rvm/gems/ruby-2.1.1/gems/ffi-compiler-0.1.3/lib/ffi-compiler/compile_task.rb:114:in `block (2 levels) in define_task!'
Tasks: TOP => default => arm-linux/libscrypt_ext.so => arm-linux/crypto_scrypt-sse.o
(See full trace by running task with --trace)

rake failed, exit code 1

Gem files will remain installed in /usr/local/rvm/gems/ruby-2.1.1/gems/scrypt-1.2.0 for inspection.
Results logged to /usr/local/rvm/gems/ruby-2.1.1/extensions/armv6l-linux/2.1.0/scrypt-1.2.0/gem_make.out
An error occurred while installing scrypt (1.2.0), and Bundler cannot continue.
Make sure that `gem install scrypt -v '1.2.0'` succeeds before bundling.
```

Any ideas?

**Comment by steakknife** [comment]
(Ping)  Have the C sources been updated yet?

**Comment by stakach** [comment]
No.. If someone can compile the original sources on ARM I'm happy to rewrite the build script to detect the platform and build appropriately

**Comment by steakknife** [comment]
I don't have a Raspberry Pi, but maybe someone else does.

What would be the necessary details they would need to post?  Configure triple, preprocessor defines (platform detection), etc.?

**Comment by stakach** [comment]
Well scrypt should build on ARM when using one of the alternative implementations
https://github.com/pbhogan/scrypt/tree/master/ext/alt-impl

Building the original implementation on ARM might be insightful too http://www.tarsnap.com/scrypt/scrypt-1.1.6.tgz

**Comment by J-F-M** [comment]
Would really love some help installing the gem onto a ARM machine...

I can build the gem using either crypto_scrypt-nosse.c or crypto_scrypt-ref.c, but rails throws an exception (cannot find 'scrypt_ext' library).

**Comment by jywarren** [comment]
Hi, all - trying to get scrypt running in an ARM (chromebook) environment, and ran into this. Has anyone made progress on it? Thanks!

**Comment by daxtens** [comment]
I've hit this on POWER too (ppc64le). Any progress on a generic solution?

**Comment by stakach** [comment]
I wrote a build script that detects ARM and SSE support, that then selects alternative implementations to compile etc however I never successfully compiled any of the implementations on ARM.

If anyone can give me cflags / ldflags or build script that will work on ARM I can make it happen.

**Comment by stakach** [comment]
Same with power arch too

**Comment by repagh** [comment]
The tests likely fail on raspberry pi because of the memory use; With 1048576 as "N", a malloc of 128*r*N+63 is made, r is 8, and in total this is requesting a G of memory.

I grabbed the updated code from the Tarsnip git, merged that in repagh/scrypt. The tarsnip code can detects & selects between different implementations. This passes the tests except for large N tests, which I commented out.  

I am new at ruby & gemfile stuff, I hope you can test from my git version.

**Comment by stakach** [comment]
I'll take a look now

**Comment by stakach** [comment]
Anyone who has a ARM PC - could you please confirm scrypt now works on the platform?

Use the following to install:
`gem install scrypt -P HighSecurity`

**Comment by petter0007** [comment]
Tried installing, but got the following error:

```
root@raspberrypi:/home/pi# gem install scrypt -P HighSecurity
Fetching: scrypt-3.0.0.gem (100%)
ERROR:  While executing gem ... (Gem::Security::Exception)
    root cert /CN=steve/DC=advancedcontrol/DC=com/DC=au is not trusted
```

**Comment by stakach** [comment]
Dang. Could you try it without HighSecurity?

`gem install scrypt`

**Comment by jywarren** [comment]
I just got v3 to install on an ARMv7 Chromebook in ubuntu trusty in a crouton environment. Nice! That had been a long-standing issue for us, thanks!

````
~$ gem install scrypt
Fetching: scrypt-3.0.0.gem (100%)
Building native extensions.  This could take a while...
Successfully installed scrypt-3.0.0
Parsing documentation for scrypt-3.0.0
Installing ri documentation for scrypt-3.0.0
Done installing documentation for scrypt after 0 seconds
1 gem installed
````

**Comment by Shelvak** [comment]
I have the same problem with Archlinux in a Rpi2 - ARMv7 .  But I can't upgrade to scrypt3, I have an old dependency :(  (authlogic--)

**Comment by daxtens** [comment]
Works on Power too :100:

**Comment by stakach** [comment]
Good to hear! Closing this issue for now. Feel free to re-open if v3.0.1 causes any issues ;)

**Comment by thepaperescape** [comment]
So, is there no solution for people like me and @Shelvak who have a dependency on an old version (2.0.2)? Can you back port the changes to make those versions compile on ARM?

**Comment by stakach** [comment]
There is no functional difference between v2 and v3 except that it runs on ARM.
Should be a drop in replacement for projects with old dependencies if those dependencies are updated.
