### ISSUE TITLE
Weak default parameters

### ISSUE THREAD

**Issue by Freaky** [pbhogan/scrypt#25]
Via [this thread](http://www.openwall.com/lists/crypt-dev/2012/09/02/1), direct quote from Colin Percival:

    > Overall, I think scrypt at 1 MiB is not a good replacement for bcrypt
    > currently.  We need bigger settings.
    
    I agree.

Suggested memory usage for [100ms is 16MB](http://www.openwall.com/lists/crypt-dev/2012/09/10/4) - perhaps a more reasonable default than 200ms/1MB?

**Comment by Freaky** [comment]
While we're at it, how about bumping that default salt size to 256 bits?  64 bits is pretty damn tiny.

**Comment by Freaky** [comment]
(Also, why salt_size but key_len?  Bit inconsistent...)

**Comment by tarcieri** [comment]
100ms is not sufficient time to make use of 16MB of memory AFAIK... you should not turn that down below 200ms.

See:

http://blog.ircmaxell.com/2014/03/why-i-dont-recommend-scrypt.html

(not that I agree with the title, but if you adopt the parameters recommended in the OP you're shooting yourself in the foot)

**Comment by Freaky** [comment]
Quoting from that: 

> bcrypt uses 4kb, which means the equivalent effective scrypt protection occurs at 4mb
>
> ...
> 
> This is why the recommendations are 16mb or higher. If you're using 16+mb of memory in scrypt (p=1, r=8 and N=2^14, or p=1, r=1 and N=17), you are fine.

**Comment by tarcieri** [comment]
Definitely a :thumbsup: on 16MB, just questioning 100ms

**Comment by Freaky** [comment]
If people are happy with 200ms now, I see no reason to reduce it, and haven't touched it in my pull request :)
