### ISSUE TITLE
Unable to install the scrypt gem on fedora 21 machine

### ISSUE THREAD

**Issue by bacancy** [pbhogan/scrypt#38]
Please help me, The gem occurs a problem on my fedora 21 server. But one more thing is it's working correctly on my local machine, which is ubuntu 14.04 machine.

Refer the below url for detailed description about the issue.

http://stackoverflow.com/questions/30352136/unable-to-install-the-scrypt-gem-on-fedora-21-machine

**Comment by stakach** [comment]
Currently the gem requires SSE CPU instructions. Basically x86 / AMD64 CPU, Pentium III or newer.
So it's not working on ARM chips at the moment

Is the fedora machine running an intel or AMD chip?

**Comment by stakach** [comment]
This should now be resolved
