### ISSUE TITLE
Scrypt sometimes picks an insane workfactor, taking 20+ seconds to compute hash

### ISSUE THREAD

**Issue by mike-bourgeous** [pbhogan/scrypt#39]
I'm currently migrating a system from a legacy password hashing scheme to scrypt.  Every now and then, scrypt is picking an insane work factor that violates the max time parameter.  I looked at the calibration source code, but didn't see an obvious cause.

Here are the limit parameters I'm setting:

```ruby
{
  key_len: 46,
  salt_size: 10,
  max_mem: 16.megabytes,
  # default max_time of 0.2
}
```

Here are the work factors I'm seeing for normal vs. insanely long hashes:

```ruby
# Normal
'4000$8$2$'

# Very long
'4000$8$186$'
```

Is there any way to prevent this from happening, or force a hard limit on the work factors?

**Comment by mike-bourgeous** [comment]
This could be the code that's going off the rails: https://github.com/pbhogan/scrypt/blob/master/ext/scrypt/scrypt_calibrate.c#L76-L80

```c
		/* Choose p based on the CPU limit. */
		maxrp = (opslimit / 4) / ((uint64_t)(1) << *logN);
		if (maxrp > 0x3fffffff)
			maxrp = 0x3fffffff;
		*p = (uint32_t)(maxrp) / *r;
```

**Comment by stakach** [comment]
Scrypt 2.0.1 is now available with your pull request. Thanks!

**Comment by mike-bourgeous** [comment]
Thanks to you, too!
