### ISSUE TITLE
Password#== timing

### ISSUE THREAD

**Issue by tyre** [pbhogan/scrypt#41]
Looking at `Password#==` ([source](https://github.com/pbhogan/scrypt/blob/master/lib/scrypt.rb#L249)), which falls back to the ruby string implementation ([2.2.0 source](http://ruby-doc.org/core-2.2.0/String.html#method-i-3D-3D)),

I don't think this protects against timing attacks. What if we included a secure comparison method similar to [this](https://github.com/rails/rails/blob/c8c660002f4b0e9606de96325f20b95248b6ff2d/activesupport/lib/active_support/security_utils.rb#L9)?

**Comment by stakach** [comment]
Thanks for pointing that out. I'll cut a new gem shortly

**Comment by tarcieri** [comment]
Password hashing functions aren't vulnerable to timing attacks. In fact,
one way to write a secure comparison function is to compute a
cryptographically secure digest of both inputs.

While this won't hurt anything, it isn't strictly necessary.

If you Google you will find some rather exotic timing attacks on unsalted
password hashing functions, but they aren't practical against salted scrypt.

There's a similar thread about this on the bcrypt gem:

https://github.com/codahale/bcrypt-ruby/pull/43

On Tuesday, July 21, 2015, Chris Maddox <notifications@github.com> wrote:

> Looking at Password#== (source
> <https://github.com/pbhogan/scrypt/blob/master/lib/scrypt.rb#L249>),
> which falls back to the ruby string implementation (2.2.0 source
> <http://ruby-doc.org/core-2.2.0/String.html#method-i-3D-3D>),
>
> I don't think this protects against timing attacks. What if we included a
> secure comparison method similar to this
> <https://github.com/rails/rails/blob/c8c660002f4b0e9606de96325f20b95248b6ff2d/activesupport/lib/active_support/security_utils.rb#L9>
> ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pbhogan/scrypt/issues/41>.
>


-- 
Tony Arcieri

**Comment by stakach** [comment]
Thanks @tarcieri I read your blog so I am fairly confident you know more about this than I do.
Happy to revert back to the native string compare. What would you do?

**Comment by tarcieri** [comment]
You can leave it as is, just keep in mind it doesn't really afford protection from attacks real-world or hypothetical

**Comment by stakach** [comment]
Appreciate the input!
