### ISSUE TITLE
permissions issue

### ISSUE THREAD

**Issue by ccutrer** [pbhogan/scrypt#43]
in version 2.1.0, lib/scrypt/security_utils.rb has permissions 0640, rather than 0644. this is causing issues for us when trying to use this gem as someone other than the person that installed the gem (in our case, the gem is installed into the bundle with the application's user, but other people use less privileged accounts to run code)

the file in the repo is properly at 0644, so this seems like something done locally accidentally before 2.1.0 was built and pushed to ruby gems

**Comment by ccutrer** [comment]
Looks good. Thanks for the quick response!

**Comment by stakach** [comment]
Anytime - thanks for letting me know
