### ISSUE TITLE
License mismatch (gemspec and COPYING file)

### ISSUE THREAD

**Issue by marcosbc** [pbhogan/scrypt#48]
Hi,

Just wanted to mention that the `COPYING` file specifies that this project is licensed under a BSD-3-Clause license, but your `scrypt.gemspec` file indicates that it is MIT licensed.

MIT was added in the Gemspec later than the `COPYING` file, so I'm guessing that MIT is the correct license, right?

Thanks!

**Comment by stakach** [comment]
Probably my bad. I would assume the BSD-3-Clause license

**Comment by pbhogan** [comment]
Yes, it's what's in the COPYING file. Although I'm not too picky.

As far as I'm concerned my primary intent is "do whatever you like with this, but we're not liable for anything that goes wrong."
