### ISSUE TITLE
Missing git tags

### ISSUE THREAD

**Issue by tiegz** [pbhogan/scrypt#51]
There are a few missing git tags from the repo:

* 2.0.1: 3d46bd9d387923537549bbdbb46ca8c8f2b60d94
* 2.0.2: a6fd7f09e75205dfda110f86395f8fab3110e4f0
* 2.1.1: c77a9629b95c53227e8122e158e991b2b4b253cc

**Comment by jaredbeck** [comment]
v3.0.0 is also missing

**Comment by stakach** [comment]
Tags added - thanks for pointing this out
