### ISSUE TITLE
travis requires activation

### ISSUE THREAD

**Issue by stakach** [pbhogan/scrypt#55]
@pbhogan would you be able to visit the following page and re-active travis?
For whatever reason it deactivated this repository and I can't re-activate it.

https://travis-ci.org/pbhogan/scrypt
![image](https://cloud.githubusercontent.com/assets/368013/16397084/a3a24d2e-3d05-11e6-8782-1667fa45e0e7.png)

**Comment by pbhogan** [comment]
Huh... weird. It's reactivated now.

**Comment by stakach** [comment]
I think it's because I added some retro-active tags and travis was confused. Thanks!
