### ISSUE TITLE
JRuby support

### ISSUE THREAD

**Issue by tarcieri** [pbhogan/scrypt#6]
Hi there.

I would love for JRuby users to be able to "gem install scrypt" and have it Just Work. This is sort of pseudo-possible with JRuby's C extension support, but that isn't production quality.

Instead, I would suggest pulling in a pure Java scrypt implementation:

https://github.com/wg/scrypt

This in turn needs to be wrapped with a JRuby Java extension that implements the SCrypt::Engine API.

This is something I'd be happy to do and contribute back upstream. The JRuby version can then ship as a -java platform gem alongside the present C-based one.

**Comment by steakknife** [comment]
It's 2 years hence but I wrapped both this gem and the jar for JRuby in a drop-in compatible gem called [`scrypt-ruby`](https://rubygems.org/gems/scrypt-ruby).  It would be better to simply merge the compatibility gunk to avoid having to get another gem and then redirect/deprecate `scrypt-ruby` in favor of `scrypt`.
