### ISSUE TITLE
Errors installing 3.0.3 on ARM (Raspberry Pi 3)

### ISSUE THREAD

**Issue by thepaperescape** [pbhogan/scrypt#62]
pi@rpi:~/fat_free_crm $ sudo gem install scrypt
Building native extensions.  This could take a while...
ERROR:  Error installing scrypt:
        ERROR: Failed to build gem native extension.

    current directory: /var/lib/gems/2.3.0/gems/scrypt-3.0.3/ext/scrypt
/usr/bin/ruby2.3 -rubygems /var/lib/gems/2.3.0/gems/rake-11.1.1/bin/rake RUBYARCHDIR=/var/lib/gems/2.3.0/extensions/arm-linux/2.3.0/scrypt-3.0.3 RUBYLIBDIR=/var/lib/gems/2.3.0/extensions/arm-linux/2.3.0/scrypt-3.0.3
mkdir -p arm-linux
/usr/bin/ruby2.3 -I/var/lib/gems/2.3.0/gems/ffi-compiler-1.0.1/lib/ffi-compiler/fake_ffi -I../../lib/scrypt /var/lib/gems/2.3.0/gems/ffi-compiler-1.0.1/lib/ffi-compiler/exporter.rb ../../lib/scrypt/scrypt_ext.rb ./scrypt_ext.h
gcc -fexceptions -O -fno-omit-frame-pointer -fno-strict-aliasing -Wall -std=c99 -D__need_timespec -fPIC   -o arm-linux/crypto_scrypt.o -c ./crypto_scrypt.c
rake aborted!
Command failed with status (127): [gcc -fexceptions -O -fno-omit-frame-pointe...]
/var/lib/gems/2.3.0/gems/ffi-compiler-1.0.1/lib/ffi-compiler/compile_task.rb:133:in `block (2 levels) in define_task!'
Tasks: TOP => default => arm-linux/libscrypt_ext.so => arm-linux/crypto_scrypt.o
(See full trace by running task with --trace)

rake failed, exit code 1

Gem files will remain installed in /var/lib/gems/2.3.0/gems/scrypt-3.0.3 for inspection.
Results logged to /var/lib/gems/2.3.0/extensions/arm-linux/2.3.0/scrypt-3.0.3/gem_make.out

**Comment by stakach** [comment]
I think response code 127 is command not found
Try running the following and installing the gem again:

```
apt-get update && apt-get upgrade
apt-get install build-essential
```

**Comment by thepaperescape** [comment]
THAT WORKED! Not your problem but you helped me through it anyways. Thank you sir!
