### ISSUE TITLE
Firebase Hash Config

### ISSUE THREAD

**Issue by mkessler** [pbhogan/scrypt#79]
I'm trying to migrate users out of Firebase, but I'm having difficulty understanding how their hash config can be used with this gem to check if a user's plaintext password matches the stored encrypted password. Here is an example of what Firebase provides:

```
hash_config {
  algorithm: SCRYPT,
  base64_signer_key:  XYZ,
  base64_salt_separator: ABC,
  rounds: 4,
  mem_cost: 8,
}
```

Any ideas on how to configure these with the gem so that I can authenticate users?

**Comment by johanns** [comment]
It seems that Firebase Scrypt implementation is purpose built and not directly compatible with most other implementations, including this gem. Although, if you can figure out the exact params used internally, you should be able to validate the passwords using this gem.

- N – iterations count (affects memory and CPU usage), e.g. 16384 or 2048
- r – block size (affects memory and CPU usage), e.g. 8
- p – parallelism factor (threads to run in parallel - affects the memory, CPU usage), usually 1
- password– the input password (8-10 chars minimal length is recommended)
- salt – securely-generated random bytes (64 bits minimum, 128 bits recommended)
- derived-key-length - how many bytes to generate as output, e.g. 32 bytes (256 bits)

You can find their implementation here: https://github.com/firebase/scrypt/

It's a CLI program -- perhaps, in the interim, you can use it to validate the passwords.

**Comment by mkessler** [comment]
@johanns - Thanks for the response. I've found this explanation of what Firebase is doing from a Firebase member here - https://github.com/firebase/scrypt/issues/2#issuecomment-548203625.

```
Sorry, Firebase doesn't use the standard Scrypt Algorithm. We use just the derived key (taken from the password, salt, and salt separator), and then do an extra round of AES using it and the project-level signing key.

You can take a look at the function scryptenc_buf_saltlen, and where it's called

We also do a layer of base64 encoding/decoding

The outline of it is:

Decrypt the User's salt, and Project's base64_signer_key and base64_salt_separator from base64

Run crypto.scrypt function with the parameters:
password = User's password
salt = User's salt + salt_separator
options.N = 2 ^ mem_cost
options.r = rounds
options.p = 1

Then take the returned derived Key, and run AES on it, with the key being the derived key, and the input being the project's signer_key (decrypted from base64)

Encode the result using base64
```
Any thoughts on making that work with this gem?
