### ISSUE TITLE
Possible to give a custom salt?

### ISSUE THREAD

**Issue by vnguyen13** [pbhogan/scrypt#84]
Hi there,

I am currently trying to migrate from Authlogic to Devise in our Ruby on Rails app. At some point in time, Authlogic switched from SHA-512 to using SCRYPT encryption. What I'm trying to do is convert our user accounts to be able to log in using their existing passwords. 

What I'm wondering is if you are familiar or have had experience with this? One thing I am trying to figure out is how to use the User's existing password_salt to generate the hash? 

Thanks for any help you can provide!

**Comment by pbhogan** [comment]
I have no experience with this, but I'd imagine you'll have to look at the Authlogic code to see exactly how it's using the password_salt. It might be some form of `SCrypt::Engine.hash_secret "mypassword", salt` but the salt scrypt uses is not just a random piece of data, it also contains the cost data. You need all all three components to decode the password: the cost data (which itself has three parts), the randomized component of the salt and the hashed secret.

Look at this part of the readme of this gem: https://github.com/pbhogan/scrypt#other-things-you-can-do
 
You'll need to figure out what's in your database from Authlogic. Did they store everything in one field as, for e.g. 
`"400$8$26$b62e0f787a5fc373$0399ccd4fa26642d92741b17c366b7f6bd12ccea5214987af445d2bed97bc6a2"`
where you can see it has the cost data, salt and password hash all together separated by `$`, which is the form this gem uses.

Once you have all those components together, use it:
```
scrypt_password = SCrypt::Password.new combined_cost_salt_hash
scrypt_password == "mypassword" # => true
```
